version: "0.1"
services:
  postgres:
    image: postgres:15
    container_name: kleep
    ports:
      - "5460:5432" # expose pg on port 5460 to not collide with pg from elsewhere
    restart: always
    volumes:
      - kleep:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "kleep-coding-game"
      POSTGRES_USER: "kleep"
      POSTGRES_PASSWORD: "kleep"
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres_is_ready:
    image: postgres
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  kleep:
